language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.24.0

matrix:
  allow_failures:
    rust: 1.24.0

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --examples

