language: rust
rust:
  - stable
  - nightly
  - 1.29.0
env:
  - BITCOINVERSION=0.18.0
  - BITCOINVERSION=0.18.1
  - BITCOINVERSION=0.19.0.1
  - BITCOINVERSION=0.19.1
  - BITCOINVERSION=0.20.0
  - BITCOINVERSION=0.20.1

script:
  - ./contrib/test.sh
