
[package]
name = "bitcoindrpc"
version = "0.0.0"
authors = ["Steven Roose <steven@stevenroose.org>"]
license = "MIT"
homepage = "https://github.com/stevenroose/rust-bitcoindrpc/"
repository = "https://github.com/stevenroose/rust-bitcoindrpc/"
documentation = "https://docs.rs/bitcoindrpc/"
description = "RPC client library for the Bitcoin Core JSON-RPC API."
keywords = [ "crypto", "bitcoin", "bitcoin core", "rpc" ]
readme = "README.md"

[lib]
name = "bitcoindrpc"
path = "src/lib.rs"

[dependencies]
jsonrpc = "0.10"

# Used for deserialization of JSON.
serde = "1"
serde_derive = "1"
serde_json = "1"
hex = "0.3"

# Used to parse difficulty values.
num-bigint = { version = "0.2", features = [ "serde" ] }

# Used for Bitcoin-specific types.
[dependencies.bitcoin-amount] # 0.1.4
version = "0.1.4"
#git = "https://github.com/jeandudey/rust-bitcoin-amount.git"
#rev = "7882b6a57762be61e8743ba7e61b6607a9e602d7"
features = [ "serde" ]

[dependencies.bitcoin]
version = "0.14.2"
features = [ "serde-decimal" ]


[patch.crates-io]
bitcoin = { path = "/home/steven/code/rust/bitcoin" }
