
[package]
name = "bitcoindrpc"
version = "0.0.0"
authors = ["Steven Roose <steven@stevenroose.org>"]
license = "CC0-1.0"
homepage = "https://github.com/stevenroose/rust-bitcoindrpc/"
repository = "https://github.com/stevenroose/rust-bitcoindrpc/"
description = "RPC client library for the Bitcoin Core JSON-RPC API."
keywords = [ "crypto", "bitcoin", "bitcoin core", "rpc" ]
readme = "README.md"

[lib]
name = "bitcoindrpc"
path = "src/lib.rs"

[dependencies]
bitcoindrpc-json = "0"
log = "0.4.5"
jsonrpc = "0.10"

# Used for deserialization of JSON.
serde = "1"
serde_json = "1"
hex = "0.3"

# Used for Bitcoin-specific types.
bitcoin = { version = "0.14.2", features = [ "serde-decimal" ] }
bitcoin-amount = { version = "0.1.4", features = [ "serde" ] }

# Used for signatures and keys
secp256k1 = { version = "0.11", features = [ "serde" ] }

# Used to parse difficulty values.
num-bigint = { version = "0.2", features = [ "serde" ] }


[patch.crates-io]
bitcoin = { path = "/home/steven/code/rust/bitcoin" }
bitcoindrpc-json = { path = "./json" }
