[package]
name = "bitcoincore-rpc-json"
version = "0.1.0"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>"
]
license = "CC0-1.0"
homepage = "https://github.com/stevenroose/rust-bitcoindrpc/"
repository = "https://github.com/stevenroose/rust-bitcoindrpc/"
description = "JSON-enabled type structs for bitcoincore-rpc crate."
keywords = [ "crypto", "bitcoin", "bitcoin-core", "rpc" ]
readme = "README.md"

[lib]
name = "bitcoincore_rpc_json"
path = "src/lib.rs"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
hex = "0.3"
bitcoin = { version = "0.15", features = [ "serde-decimal" ] }
bitcoin-amount = { version = "0.1.4", features = [ "serde" ] }
secp256k1 = { version = "0.11", features = [ "serde" ] }
num-bigint = { version = "0.2", features = [ "serde" ] }
